# Плагин kRTP разработан vk.com/yacushev для "KleksyStudio"
# Версия 2.1
# Покупка плагина: https://vk.me/kleksystudio
# *Продажа/слив/передача запрещена!
RTP:
 # Сколько будет отниматься голода при телепортации(если не нужно, то ставить 0)
 FoodLevel: 6
Messages:
 teleport: '&AВы успешно телепортированы'
 nofood: '&aУ вас недостаточно голода, поешьте!'
 noplayer: '&cПоблизости нет игроков!'
 noPermission: '&cУ вас нет прав!'
 OnlyPlayer: '&cКоманду можно выполнять только от имени игрока!'